version: 2.1

executors:
  php-81:
    docker:
      - image: cimg/php:8.1

orbs:
  php: circleci/php@1.1.0

commands:
  enable_extensions:
    steps:
      - run:
          name: Install pcov
          command: sudo pecl -vvv install pcov
  create_reports_directory:
    steps:
      - run:
          name: Create reports directory
          command: mkdir ~/reports
  install_composer:
    steps:
      - php/install-composer

  install_composer_packages:
    steps:
      - php/install-packages:
          install-flags: --no-interaction --prefer-dist
          cache-version: php-81-v1
          cache-key: composer.json

jobs:
  composer_validate:
    executor: php-81
    steps:
      - checkout
      - install_composer
      - run:
          name: Validate composer file
          command: composer validate --no-interaction --ansi
  static_analysis:
    executor: php-81
    steps:
      - checkout
      - enable_extensions
      - install_composer
      - install_composer_packages
      - create_reports_directory
      - run:
          name: Unit Tests
          command: php -d pcov.enabled=1 vendor/bin/phpunit --coverage-html ~/reports/code-coverage
          environment:
            XDEBUG_MODE: coverage
      - store_artifacts:
          path: ~/reports/code-coverage
          destination: code-coverage
      - run:
          name: PHPStan
          command: vendor/bin/phpstan analyze --memory-limit=-1 --error-format=prettyJson | tee ~/reports/phpstan.json
      - store_artifacts:
          path: ~/reports/phpstan.json
          destination: phpstan.json
      - run:
          name: Psalm
          command: |
            sudo apt update
            sudo apt install xsltproc
            composer require --dev roave/psalm-html-output
            vendor/bin/psalm --output-format=xml | xsltproc vendor/roave/psalm-html-output/psalm-html-output.xsl - > ~/reports/psalm.html
      - store_artifacts:
          path: ~/reports/psalm.html
          destination: psalm.html
      - run:
          name: PHP Mess Detector
          command: vendor/bin/phpmd src,tests html phpmd.xml --reportfile ~/reports/phpmd.html
      - store_artifacts:
          path: ~/reports/phpmd.html
          destination: phpmd.html
      - run:
          name: Infection
          command: php -d pcov.enabled=1 -d memory_limit=-1 vendor/bin/infection --threads=4 --min-msi=100 --min-covered-msi=100
      - store_artifacts:
          path: reports/infection.html
          destination: infection.html
      - run:
          name: Psalm Security Analysis
          command: vendor/bin/psalm --taint-analysis --report=reports/psalm-security.sarif
      - store_artifacts:
          path: reports/psalm-security.sarif
          destination: psalm-security.sarif

workflows:
  build:
    jobs:
      - composer_validate
      - static_analysis:
          requires:
            - composer_validate
